import './globals.css'
import Navber from '../components/Navber/Navber'
import Footer from '../components/Footer/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <Navber/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
